Feature/add user
brunasouza2/nosso-mercado-livre pull request #1
Opened 2020-04-09 03:22 UTC by brunasouza2

Validando e adicionando usuario ao sistema.

2020-04-09 09:58 UTC, asouza requested changes

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/controller/UserController.java
> +    public ResponseEntity<String> addUser(@RequestParam String login, @RequestParam String password,
Admito que gosto da simplicidade de receber logo direto aqui, já que são apenas poucos parâmetros mesmo :).

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/controller/UserController.java
> +    public ResponseEntity<String> addUser(@RequestParam String login, @RequestParam String password,
Aqui eu sei que o @RequestParam já ensina o spring que a presença é obrigatória. Por outro lado ele não verifica se o texto ta preenchido, se a senha tem 6 caracteres e tem texto e por aí. Minha sugestão é você colocar aqui as annotations de validação e anotar a classe com @Validated. Assim a validação vai ser aplicada direta nos parâmetros.

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/controller/UserController.java
> +    public ResponseEntity<String> addUser(@RequestParam String login, @RequestParam String password,
O instante é uma informação de controle do sistema e não pode ser definida por ninguém no código. Se você aceita um argumento no construtor, alguém pode passar um instante diferente do real.

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/controller/UserController.java
> +        repository.save(new User(login, passwordEncoded, instant));
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*

A pergunta aqui é: se não fosse você que tivesse escrito o código de chamada do construtor, como você ia saber que era necessário encodar essa senha? O que você pode fazer para facilitar esse entendimento?

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/dto/User.java
> +@Getter
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Não precisamos de getter e setter agora. Setter principalmente, pq permitiria a alteração parcial do objeto.

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/dto/User.java
> +public class User implements Serializable {
Pq ela implementa Serializable? Digo, para o Hibernate isso não é necessário.

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/dto/User.java
> +    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
*Separamos as bordas externas do sistema do seu núcleo. Não ligamos parâmetros de requisição externa com objetos de domínio diretamente, assim como não serializamos objetos de domínio para respostas de API.*

O JsonFormat assume que você planeja serializar esse objeto e a gente evita conectar classes de domínio com pontos externos do sistema, justamente por conta da facilidade de quebra de contrato. Se você tirar ou colocar um getter aqui, alteraria o retorno de algum endpoint.

2020-04-09 09:58 UTC, asouza commented on src/main/java/br/com/dev/eficiente/nosso/mercado/livre/dto/User.java
> +                @NotNull @Past @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss") LocalDateTime instant){
Comentário similar ao JsonFormat de cima. E neste ponto aqui, assim como em cima, o formato da data não é mais importante para você. Isso só conta na hora de receber o parâmetro lá na rota, já que lá você converter da string para data.

2020-04-10 01:42 UTC, closed without merging

2020-04-10 01:42 UTC, brunasouza2 commented
Ajustes aplicados